kind: pipeline
type: docker

name: build-and-push

steps:
  - name: push
    image: plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      registry: registry.simon-petrik.de
      repo: registry.simon-petrik.de/email-filter
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
