kind: pipeline
type: docker

name: build-and-push

steps:
  - name: build
    image: docker:latest
    environment:
      DOCKER_BUILDKIT: 1
    commands:
      - docker build -t email-filter:latest .
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: push
    image: plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      repo: registry.simon-petrik.de/email-filter:latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags: latest

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
